import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const roboto = Roboto_Mono({ weight: "variable", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
