import { Roboto_Mono } from "next/font/google";
import "./globals.css";

//font config --> the variable weight allows us to change the weight of the font with styles
const roboto = Roboto_Mono({ weight: "variable", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
