import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
//import ClerkProvider to allow Clerk to access our app
import { ClerkProvider } from "@clerk/nextjs";

const roboto = Roboto_Mono({ weight: "variable", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // I am nesting my app into ClerkProvider
    <ClerkProvider>
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
