//this file is the blueprint for all pages --> this layout is in the root
import { Geist, Geist_Mono } from "next/font/google";
import Header from "@/components/Header"; // the @ symbol is an abbreviation of ./src/*
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {/* the children property contains the elements rendered in our pages. For example, if we navigate to the home page, children will represent the home page elements */}
        {children}
      </body>
    </html>
  );
}
